FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements-trello.txt .
RUN pip install --no-cache-dir -r requirements-trello.txt

# Копирование скриптов
COPY trello_to_excel_v2.py .

# Создание директории для файлов
RUN mkdir -p /app/files

CMD ["python3", "trello_to_excel_v2.py"]
